### ISSUE TITLE
Realtidsinformation 4

### ISSUE THREAD

**Issue by teolag** [simon-johansson/SL-api#3]
Hej!
Det ser ut som Trafiklab inte stödjer realtidsinformation 3 längre utan kör nu 4.
Har du lust och tid att uppdatera tror du? Ser att det är fler som väntar på en uppdatering och till och med gjort pull-requests åt dig =)
Tack!

**Comment by simon-johansson** [comment]
Ledsen för att det har dröjt 😔
Har nu dragit en PR:en och släppt en ny version av modulen.

**Comment by teolag** [comment]
Kanon! Tack så mycket!
